import { cn } from "@/lib/utils";
import { Info, ShieldAlert, Sparkles } from "lucide-react";
import type { ReactNode } from "react";
import type { AIDisclaimerVariant } from "./types";

export interface AIDisclaimerProps {
  variant?: AIDisclaimerVariant;
  /** Required for `variant="custom"`; overrides the preset copy otherwise. */
  message?: ReactNode;
  size?: "sm" | "md";
  className?: string;
}

/*
 * Preset copy, kept here rather than at call sites so the wording is reviewed
 * once and stays consistent. Compliance language that varies screen to screen
 * reads as boilerplate and gets ignored.
 */
const variantConfig: Record<
  Exclude<AIDisclaimerVariant, "custom">,
  { message: string; icon: ReactNode; className: string }
> = {
  "review-required": {
    message:
      "AI-generated suggestion. A qualified person must review and approve before this is submitted.",
    icon: <ShieldAlert className="h-3.5 w-3.5 shrink-0" aria-hidden="true" />,
    className: "bg-warning-container text-warning-on-container border-warning-border",
  },
  "not-diagnostic": {
    message:
      "Not a diagnostic tool. This output does not constitute a clinical interpretation and must not be used for diagnosis.",
    icon: <ShieldAlert className="h-3.5 w-3.5 shrink-0" aria-hidden="true" />,
    className: "bg-danger-container text-danger-on-container border-danger-border",
  },
  generated: {
    message: "Generated by AI. May contain errors — verify before relying on it.",
    icon: <Sparkles className="h-3.5 w-3.5 shrink-0" aria-hidden="true" />,
    className: "bg-ai-surface text-ai-on-surface border-ai-border",
  },
};

/**
 * Standing notice attached to AI output.
 *
 * Pair `review-required` with anything that can reach a claim or a patient
 * record, and `not-diagnostic` with anything touching imaging interpretation.
 *
 * Rendered as a plain `<p>`, not an `alert` or live region: this is persistent
 * context, so announcing it on every render would interrupt the content it is
 * meant to qualify. It sits in the reading order right beside the output, which
 * is where a screen reader user encounters it naturally.
 */
export function AIDisclaimer({
  variant = "generated",
  message,
  size = "sm",
  className,
}: AIDisclaimerProps) {
  if (variant === "custom" && !message) {
    if (process.env.NODE_ENV !== "production") {
      console.warn('[AIDisclaimer] variant="custom" requires a `message`.');
    }
    return null;
  }

  const config = variant === "custom" ? null : variantConfig[variant];

  return (
    <p
      className={cn(
        "flex items-start gap-1.5 rounded-lg border px-2.5 py-1.5 leading-snug",
        size === "sm" ? "text-[11px]" : "text-xs",
        config?.className ?? "bg-surface-container text-on-surface-variant border-outline-variant/40",
        className
      )}
    >
      {config?.icon ?? <Info className="h-3.5 w-3.5 shrink-0" aria-hidden="true" />}
      <span>{message ?? config?.message}</span>
    </p>
  );
}
